# Generated by Django 5.0.6 on 2024-05-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_materiel', '0002_alter_enseignant_nom_alter_enseignant_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(default='aucun', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(default='aucun', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salle',
            name='nom',
            field=models.CharField(default='aucun', max_length=50, null=True),
        ),
    ]
